env:
  browser: true
  es6: true
  node: true
extends:
  - 'plugin:react/recommended'
  - google
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
rules: {
  object-curly-spacing: ["error", "always",
                         { "objectsInObjects": false,
                           "arraysInObjects": false
                         }],
  "require-jsdoc": ["error", {
    "require": {
      "FunctionDeclaration": false,
      "MethodDefinition": false,
      "ClassDeclaration": false,
      "ArrowFunctionExpression": false,
      "FunctionExpression": false
    }
  }]
}
